export const GET_ALL_FLIGHTS = 'GET_ALL_FLIGHTS';
export const GET_SINGLE_FLIGHT = 'GET_SINGLE_FLIGHT';
export const BOOK_FLIGHT = 'BOOK_FLIGHT';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';

export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const SORT_BY_POPULARITY = 'SORT_BY_POPULARITY';
export const SORT_BY_CHEAPEST_PRICE = 'SORT_BY_CHEAPEST_PRICE';
export const SORT_BY_SHORTEST_FLIGHT = 'SORT_BY_SHORTEST_FLIGHT';