export const GET_ALL_FLIGHTS = "GET_ALL_FLIGHTS";
export const BOOK_FLIGHT = "BOOK_FLIGHT";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const DISPLAY_ALL_CLASSES = "DISPLAY_ALL_CLASSES";
export const FIND_ECONOMY_CLASS = "FIND_ECONOMY_CLASS";
export const FIND_BUSINESS_CLASS = "FIND_BUSINESS_CLASS";
export const FIND_FIRST_CLASS = "FIND_FIRST_CLASS";

export const SORT_BY_POPULARITY = "SORT_BY_POPULARITY";
export const SORT_BY_CHEAPEST_PRICE = "SORT_BY_CHEAPEST_PRICE";
export const SORT_BY_EXPIRATION_DATE = "SORT_BY_EXPIRATION_DATE";
export const SORT_BY_SHORTEST_FLIGHT = "SORT_BY_SHORTEST_FLIGHT";

export const ADD_USER_INFO = "ADD_USER_INFO";
